name: hds_logistics
channels:
  - defaults
  - conda-forge
dependencies:
  - contextily=1.0.0
  - folium=0.11.0
  - geopandas=0.8.1
  - geoplot=0.4.1
  - jupyterlab=2.2.6
  - mapclassify=2.3.0
  - matplotlib=3.3.1
  - numpy=1.19.1
  - pandas=1.1.2
  - pip=20.2.3
  - pysal=2.3.0
  - python=3.7.7
  - scipy=1.5.2
  - seaborn=0.11.0
